; =====================================================================
; SP-Farms Windows Installer Script (Inno Setup 6+)
; =====================================================================
; Ensures:
; - Standard 64-bit Windows installation under {autopf}\SP-Farms
; - Application shortcuts on Desktop and Start Menu
; - UPGRADE-SAFE data location: User database, backups, and logs reside
;   in %APPDATA%\SP-Farms and %LOCALAPPDATA%\SP-Farms
; - UNINSTALL BEHAVIOR: Preserves user database (.db), exports, backups (.spbackup)
;   unless explicitly checked by the operator during uninstallation.
; =====================================================================

#define MyAppName "SP-Farms"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "SP-Farms"
#define MyAppURL "https://github.com/Sempanha123/SP-Farms"
#define MyAppExeName "SP-Farms.exe"

[Setup]
AppId={{D5F8A28E-6C0D-48E9-B5FA-71C694FEE921}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
OutputDir=..\dist\installer
OutputBaseFilename=SP-Farms-Setup-{#MyAppVersion}
SetupIconFile=..\assets\icons\sp_farms.ico
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=yes
RestartApplications=no
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Distributable application bundle generated by PyInstaller
Source: "..\dist\SP-Farms\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icons\sp_farms.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icons\sp_farms.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Custom Pascal Script to guarantee safety of operator databases and credentials
var
  RemoveDataCheckbox: TNewCheckBox;

procedure InitializeUninstallProgressForm();
var
  DataDir: String;
begin
  DataDir := ExpandConstant('{userappdata}\SP-Farms');
  if DirExists(DataDir) then
  begin
    RemoveDataCheckbox := TNewCheckBox.Create(UninstallProgressForm);
    RemoveDataCheckbox.Parent := UninstallProgressForm;
    RemoveDataCheckbox.Caption := 'Delete all user databases, backups, and saved configurations';
    RemoveDataCheckbox.Left := ScaleX(20);
    RemoveDataCheckbox.Top := UninstallProgressForm.CancelButton.Top;
    RemoveDataCheckbox.Width := ScaleX(360);
    RemoveDataCheckbox.Checked := False; // Default UNCHECKED to protect user data
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
  LogDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    DataDir := ExpandConstant('{userappdata}\SP-Farms');
    LogDir := ExpandConstant('{localappdata}\SP-Farms');

    // Only remove user data if explicitly requested
    if Assigned(RemoveDataCheckbox) and RemoveDataCheckbox.Checked then
    begin
      if DirExists(DataDir) then
        DelTree(DataDir, True, True, True);
      if DirExists(LogDir) then
        DelTree(LogDir, True, True, True);
    end;
  end;
end;
