"""Hexagonal port and abstract client interface for Appium 2 driver operations."""

from collections.abc import Mapping
from typing import Any, Protocol

from sp_farms.domain.automation import (
    AppState,
    By,
    ElementRef,
    UiAutomator2Capabilities,
)


class AppiumDriverPort(Protocol):
    """Abstract port for W3C / Appium 2 UiAutomator2 driver commands."""

    def create_session(
        self, server_url: str, capabilities: UiAutomator2Capabilities
    ) -> str: ...  # returns session_id

    def delete_session(self, session_id: str) -> None: ...

    def is_session_alive(self, session_id: str) -> bool: ...

    def activate_app(self, session_id: str, app_id: str) -> None: ...

    def terminate_app(self, session_id: str, app_id: str) -> bool: ...

    def query_app_state(self, session_id: str, app_id: str) -> AppState: ...

    def get_current_activity(self, session_id: str) -> str: ...

    def get_current_package(self, session_id: str) -> str: ...

    def get_page_source(self, session_id: str) -> str: ...

    def take_screenshot(self, session_id: str) -> bytes: ...

    def find_element(self, session_id: str, by: By, value: str) -> ElementRef: ...

    def find_elements(self, session_id: str, by: By, value: str) -> list[ElementRef]: ...

    def click(self, session_id: str, element_id: str) -> None: ...

    def type_text(self, session_id: str, element_id: str, text: str) -> None: ...

    def clear_text(self, session_id: str, element_id: str) -> None: ...

    def get_element_text(self, session_id: str, element_id: str) -> str: ...

    def get_element_attribute(self, session_id: str, element_id: str, name: str) -> str | None: ...

    def is_element_displayed(self, session_id: str, element_id: str) -> bool: ...

    def is_element_enabled(self, session_id: str, element_id: str) -> bool: ...

    def tap_coordinates(self, session_id: str, x: int, y: int) -> None: ...

    def swipe(
        self,
        session_id: str,
        start_x: int,
        start_y: int,
        end_x: int,
        end_y: int,
        duration_ms: int = 800,
    ) -> None: ...

    def press_key_code(self, session_id: str, keycode: int) -> None: ...

    def press_back(self, session_id: str) -> None: ...

    def execute_script(
        self, session_id: str, script: str, args: list[Any] | None = None
    ) -> Any: ...
