"""Campaign repository port interface."""

from collections.abc import Sequence
from typing import Protocol

from sp_farms.domain.campaigns import Campaign, CampaignStatus, CampaignTarget


class CampaignRepositoryPort(Protocol):
    def save_campaign(self, campaign: Campaign) -> Campaign: ...
    def get_campaign(self, campaign_id: str) -> Campaign | None: ...
    def list_campaigns(
        self,
        status: CampaignStatus | None = None,
        search: str | None = None,
        include_archived: bool = False,
    ) -> Sequence[Campaign]: ...
    def delete_campaign(self, campaign_id: str) -> bool: ...
    def save_target(self, target: CampaignTarget) -> CampaignTarget: ...
    def get_target(self, target_id: str) -> CampaignTarget | None: ...
    def list_targets(self, campaign_id: str) -> Sequence[CampaignTarget]: ...
    def delete_target(self, target_id: str) -> bool: ...
