from collections.abc import Sequence
from typing import Protocol

from sp_farms.domain.jobs import Job, JobEvent


class JobRepository(Protocol):
    def add(self, job: Job) -> None: ...

    def get(self, job_id: str) -> Job | None: ...

    def find_by_idempotency_key(self, key: str) -> Job | None: ...

    def list_all(self) -> Sequence[Job]: ...

    def list_active(self) -> Sequence[Job]: ...

    def add_event(self, event: JobEvent) -> None: ...

    def list_events(self, job_id: str) -> Sequence[JobEvent]: ...
